"""Comment reply prompt layer, owned by docich (#829 PR-3a).

Native port of the prompt stage of soviet_now ``broadcast/comment.sh``
(``generate_comment_response`` / ``_build_category_prompt`` /
``_build_gacha_completion_note`` / ``_sanitize_comment_prompt_context`` /
``_append_comment_reply_contract``, as wrapped by ``comment_runtime_policy.sh``).
Every function here is pure except
``gacha_completion_note``, which keeps the legacy "celebrate a completion
once" list file. Behaviour is pinned byte-for-byte by
``tests/fixtures/comment_prompt_golden.json``, generated by executing the
legacy shell (``scripts/golden/comment_prompt_golden.py``).

The prompt assets live in ``prompts/`` next to this module and are the
canonical copies for the native pipeline. Context *values* (persona aside)
are supplied by the caller; building them is a later PR-3 slice.
"""
from __future__ import annotations

import os
from pathlib import Path
import re

PROMPTS_DIR = Path(__file__).with_name("prompts")

# The legacy envsubst allowlists, in their original order.
MIXED_TEMPLATE_VARS = (
    "_comment_persona", "current_time", "time_period", "twitch_comments_for_prompt",
    "comment_batch_context", "strategy_advice_candidates", "comment_advice_candidates",
    "codex_advice_candidates", "comment_advice_context", "previous_comments_context",
    "recent_spoken_comment_context", "viewer_memory_context", "comment_followup_hints",
    "past_topics", "celebration_history_context", "comment_thumbnail_ocr_context",
    "PAST_RADIO_TOPICS", "RUSSIA_CREATION_HISTORY_FILE", "SOVIET_CREATION_HISTORY_FILE",
    "ROLLING_SCORES_FILE", "game_state_context", "comment_ops_context", "_comment_ui_memo",
    "_comment_channel_intro", "_comment_length_policy", "sing_reference", "_prediction_cycle_games",
)
CATEGORY_TEMPLATE_VARS = (
    "CATEGORY_COMMENTS", "COMMENT_CLASSIFICATIONS", "twitch_comments_for_prompt", "_comment_persona",
    "current_time", "time_period", "comment_batch_context", "strategy_advice_candidates",
    "comment_advice_candidates", "codex_advice_candidates", "comment_advice_context",
    "previous_comments_context", "recent_spoken_comment_context", "viewer_memory_context",
    "comment_followup_hints", "past_topics", "celebration_history_context",
    "comment_thumbnail_ocr_context", "PAST_RADIO_TOPICS", "RUSSIA_CREATION_HISTORY_FILE",
    "SOVIET_CREATION_HISTORY_FILE", "ROLLING_SCORES_FILE", "game_state_context", "comment_ops_context",
    "_comment_ui_memo", "_comment_channel_intro", "_comment_length_policy", "sing_reference",
    "_prediction_cycle_games", "gacha_completion_note",
)
MODES = ("main", "soren91")
NONE = "（なし）"
NO_GACHA_NOTE = "（今回はコンプリート関連の特記事項はありません。）"

# GNU envsubst identifiers are ASCII; a Unicode \w would swallow "$nameの".
_VAR_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)")


def asset(name: str) -> str:
    return (PROMPTS_DIR / name).read_text(encoding="utf-8")


def envsubst(template: str, names, values) -> str:
    """``envsubst 'NAMES'``: replace only the listed ``$NAME``/``${NAME}``, once.

    Unlisted references stay verbatim; a listed name without a value becomes
    empty (an unset variable); substituted values are never re-expanded.
    """
    allowed = frozenset(names)

    def replace(match):
        name = match.group(1) or match.group(2)
        return values.get(name, "") if name in allowed else match.group(0)
    return _VAR_RE.sub(replace, template)


def mode_assets(mode: str) -> dict[str, str]:
    """Persona / UI memo / channel intro / length policy of the host mode.

    Like the legacy ``$(cat file)``, trailing newlines are dropped.
    """
    if mode not in MODES:
        raise ValueError("unknown_mode")
    return {
        "_comment_persona": asset(f"comment_persona_{mode}.md").rstrip("\n"),
        "_comment_ui_memo": asset(f"comment_ui_memo_{mode}.md").rstrip("\n"),
        "_comment_channel_intro": asset(f"comment_channel_intro_{mode}.md").rstrip("\n"),
        "_comment_length_policy": asset("comment_length_policy_soren91.md") if mode == "soren91" else "",
    }


def time_period(hour: int) -> str:
    if 5 <= hour < 9:
        return "朝"
    if 9 <= hour < 12:
        return "午前"
    if 12 <= hour < 17:
        return "午後"
    if 17 <= hour < 21:
        return "夕方"
    if hour >= 21 or hour < 2:
        return "夜"
    return "未明"


_ERROR_PATTERNS = [re.compile(p, re.I) for p in (
    r"申し訳(?:ありません|ございません|ない).*(?:エラーメッセージ|提供|ユーザーメッセージ|指示|タスク|情報|スクリーンショット)",
    r"(?:エラーメッセージ|ユーザーメッセージ|具体的な指示|明確な指示|具体的なタスク).*(?:提供されてい|見当たりません|ありません|ない|不足)",
    r"(?:何も言えません|語ることはできません|控えておくべき|確認させてください|どうすればよい|何を.*すれば)",
    r"(?:tool_call|tool_result|assistant_response|System Context|permission denied|no such file or directory|file not found|read failed|edit failed|write failed)",
    r"(?:unexpected token|syntaxerror|referenceerror|typeerror|could not find oldstring|no changes to apply|rejected permission)",
    r"(?:invalid bearer token|authentication_error|api error|request_id|invalid token|not logged in|please run /login|rate limit|too many requests|429\b|quota|usage limit)",
    r"(?:ユーザーからの.*指示がなく|システム設定.*だけが提供|具体的なタスク指示が見当たりません)",
    r"(?:提供いただいた|提供していただいた).*(?:実際の記事本文|本文ではなく|テンプレート|管理情報|テキスト).*?(?:含まれていない|ありません|成立していません)",
    r"(?:検索|WebFetch|インターネット|外部.*アクセス).*(?:できません|ありません|許可|確認できません)",
)]


def _bad_context_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if re.match(r"^(error|warning)\s*:", stripped, re.I):
        return True
    if re.match(r"^[✗✕×].*\b(read|glob|grep|ls|edit|write|multiedit)\b.*\bfailed\b", stripped, re.I):
        return True
    if re.match(r"^[✱→►▸]\s*(read|glob|grep|ls|edit|write|multiedit)\b", stripped, re.I):
        return True
    return any(pattern.search(stripped) for pattern in _ERROR_PATTERNS)


def sanitize_context(text: str) -> str:
    """Drop provider error / tool-log lines and blank lines; empty -> "（なし）"."""
    kept = [raw.rstrip() for raw in text.splitlines() if not _bad_context_line(raw)]
    joined = "\n".join(line for line in kept if line.strip()).strip()
    return joined if joined else NONE


def with_defaults(ctx: dict) -> dict:
    """The legacy "Pre-resolve defaults for envsubst" step (empty/unset -> placeholder)."""
    out = dict(ctx)

    def default(name, value):
        return out.get(name) or value
    for name in ("comment_batch_context", "strategy_advice_candidates", "comment_advice_candidates",
                 "codex_advice_candidates", "comment_advice_context"):
        out[name] = default(name, NONE)
    for name, value in (("previous_comments_context", NONE), ("recent_spoken_comment_context", NONE),
                        ("viewer_memory_context", "（該当する投稿者別メモなし）"),
                        ("comment_followup_hints", NONE)):
        out[name] = sanitize_context(default(name, value))
    out["celebration_history_context"] = default("celebration_history_context", NONE)
    out["comment_thumbnail_ocr_context"] = sanitize_context(default("comment_thumbnail_ocr_context", NONE))
    out["game_state_context"] = sanitize_context(default("game_state_context", "（取得失敗）"))
    out["comment_ops_context"] = sanitize_context(default("comment_ops_context", "（取得失敗）"))
    return out


def dominant_category(rows) -> str | None:
    """>80% share (or the only category) wins, otherwise "mixed"; None when unusable."""
    if not isinstance(rows, list) or not rows:
        return None
    counts: dict[str, int] = {}
    try:
        for item in rows:
            category = item.get("category", "chitchat")
            counts[category] = counts.get(category, 0) + 1
    except (AttributeError, TypeError):
        return None  # the legacy inline script exits 1
    dominant = max(counts, key=counts.get)
    if counts[dominant] / len(rows) > 0.8 or len(counts) == 1:
        return dominant
    return "mixed"


def english_count(rows) -> int:
    return sum(1 for row in rows if isinstance(row, dict) and row.get("is_english") is True) \
        if isinstance(rows, list) else 0


def format_classifications(rows, batch_lines) -> str:
    """``[i] user: comment -> category -> english|japanese/other`` per classified line.

    Malformed input yields "" as a whole, like the legacy script whose failure
    was swallowed (``2>/dev/null``).
    """
    try:
        return _format_classifications(rows, batch_lines)
    except (AttributeError, TypeError):
        return ""


def _format_classifications(rows, batch_lines) -> str:
    source = [line for line in batch_lines if line.strip()]
    out = []
    for item in rows:
        try:
            idx = int(item.get("index", 0))
        except Exception:
            idx = 0
        if 1 <= idx <= len(source):
            raw = source[idx - 1]
            user, comment = raw.split(": ", 1) if ": " in raw else ("", raw)
        else:
            user, comment = "", ""
        category = item.get("category", "chitchat")
        english = "english" if item.get("is_english") is True else "japanese/other"
        if comment:
            out.append(f"[{idx}] {user}: {comment} -> {category} -> {english}")
    return "\n".join(out)


_GACHA_COUNT_RE = re.compile(r"(\d+)\s*種中\s*(\d+)\s*種所持")


def _gacha_user(line: str) -> str:
    s = line.strip()
    if ": " in s:
        head, rest = s.split(": ", 1)
        m = re.match(r"\s*@?([^\s　:]+)\s*が", rest)
        if m:
            return m.group(1).lstrip("@")
        h = head.strip().lstrip("@")
        if h and not h.startswith("["):
            return h
        s = rest.strip()
    m = re.match(r"\s*@?([^\s　:]+)\s*が", s)
    return m.group(1).lstrip("@") if m else ""


def gacha_completion_note(comments_block: str, list_file: Path) -> str:
    """Celebrate a full card-set completion once per viewer; records first completions."""
    if not comments_block:
        return ""
    known: dict[str, str] = {}
    try:
        with open(list_file, encoding="utf-8", errors="ignore") as stream:
            for line in stream:
                name = line.strip()
                if name:
                    known.setdefault(name.lower(), name)
    except FileNotFoundError:
        pass
    already, newly, newly_keys = [], [], set()
    for raw in comments_block.splitlines():
        line = raw.strip()
        if not line:
            continue
        m = _GACHA_COUNT_RE.search(line)
        if not m:
            continue
        total, owned = int(m.group(1)), int(m.group(2))
        if total <= 0 or owned < total:
            continue
        user = _gacha_user(line)
        if not user:
            continue
        key = user.lower()
        if key in known:
            if known[key] not in already:
                already.append(known[key])
            continue
        if key in newly_keys:
            continue
        newly_keys.add(key)
        newly.append(user)
    if newly:
        try:
            Path(list_file).parent.mkdir(parents=True, exist_ok=True)
            with open(list_file, "a", encoding="utf-8") as stream:
                for user in newly:
                    stream.write(user + "\n")
        except OSError:
            pass
    out = []
    if already:
        out.append("次のユーザーは過去に全種コンプリート達成済みで、既に何度も祝福しています: " + "、".join(already) + "。")
        out.append("このユーザーにはコンプリート・全種制覇・制覇・112種制覇といった達成自体には一切触れず、今回引いたカードそのものの話だけをしてください。")
    if newly:
        out.append("次のユーザーは今回が初のコンプリート達成です: " + "、".join(newly) + "。一度だけ達成を祝ってください。")
    return "\n".join(out)


def category_template(category: str) -> str:
    template = {"game_question": "game", "game_status": "game",
                "strategy_advice": "default", "comment_advice": "default", "general_question": "default",
                "subscription": "default", "stream_goal": "default", "bits": "default",
                "other": "default"}.get(category, category)
    path = PROMPTS_DIR / f"comment_response_{template}.md"
    return path.name if path.is_file() else "comment_response_default.md"


def build_prompt(category: str | None, ctx: dict, *, comments_block: str, classifications: str,
                 gacha_list_file: Path) -> str:
    """The base prompt: category template, or ``comment_template.md`` for mixed/unknown."""
    if category and category != "mixed":
        note = gacha_completion_note(comments_block, gacha_list_file) if category == "card_gacha" else ""
        values = {**ctx, "CATEGORY_COMMENTS": comments_block, "COMMENT_CLASSIFICATIONS": classifications,
                  "twitch_comments_for_prompt": comments_block, "gacha_completion_note": note or NO_GACHA_NOTE}
        return envsubst(asset(category_template(category)), CATEGORY_TEMPLATE_VARS, values)
    return envsubst(asset("comment_template.md"), MIXED_TEMPLATE_VARS, ctx)


def with_reply_contract(prompt: str) -> str:
    """Append the output/factuality contract, the speech vocabulary rule, and the
    viewer-address / card-burst contract.

    The last block is what production actually appends: soviet_now's
    ``comment_runtime_policy.sh`` wraps ``_append_comment_reply_contract``
    after ``comment.sh`` is loaded.
    """
    return (prompt + asset("comment_reply_contract.md") + "\n" + asset("speech_vocabulary_rule.md")
            + asset("comment_reply_policy_contract.md"))


def retry_prompt(prompt: str, mode: str) -> str:
    """Attempt >1: the legacy regeneration addendum (+ the mode's retry length policy)."""
    out = prompt + asset("comment_retry_addendum.md")
    if mode == "soren91":
        out += asset("comment_retry_length_policy_soren91.md") + "\n"
    return out


def gacha_list_file(env=None) -> Path:
    env = os.environ if env is None else env
    return Path(env.get("GACHA_COMPLETED_USERS_FILE")
                or f"{env.get('TMP_HISTORY_DIR') or 'tmp/history'}/gacha_completed_users.txt")


__all__ = ["asset", "build_prompt", "category_template", "dominant_category", "english_count",
           "envsubst", "format_classifications", "gacha_completion_note", "gacha_list_file",
           "mode_assets", "retry_prompt", "sanitize_context", "time_period", "with_defaults",
           "with_reply_contract"]
