"""Comment runtime state (dedup / inflight / backoff / history), owned by docich (#829 PR-3c).

Native port of the state helpers of soviet_now ``broadcast/comment.sh`` with the
**same on-disk formats and paths** (relative to the Soren root), so the native
pipeline can take over the live files at cutover without a migration:

- ``tmp/.comment_queue/processed_batch_hashes.log``  ``<epoch>|<batch md5>``
- ``tmp/.comment_queue/inflight_batch.log``          ``<epoch>|<batch md5>|<pid>``
- ``tmp/.comment_queue/processed_line_hashes.log``   ``<epoch>|<line md5>``
- ``tmp/state/comment_generation_backoff_until``     ``<epoch>``
- ``tmp/.comment_queue/spoken_history/`` + ``.reply_hashes``
- ``tmp/history/comment_generation_history.jsonl`` and ``*.meta.json`` sidecars

Behaviour (TTL arithmetic, awk field/number semantics, ``read`` splitting,
``tail`` caps) is pinned by ``tests/fixtures/comment_state_golden.json``,
generated by executing the legacy on Linux with a fixed clock. Every time
dependence takes ``now`` so callers and tests control the clock.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import time

# core/config.sh constants (hard-coded there, not env-overridable).
COMMENT_BATCH_DEDUP_TTL = 900
COMMENT_PROCESSED_LINES_TTL = 1800
COMMENT_PROCESSED_LINES_MAX = 500


def hash_text(text: str) -> str:
    """``_outbound_chat_hash``: md5 of ``printf '%s'``."""
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def dedup_key(line: str) -> str:
    """Drop a leading ``user: `` so rotated accounts spamming one body collide."""
    if ": " in line:
        head, rest = line.split(": ", 1)
        if not head.endswith(" "):
            return rest
    return line


def _awk_num(field: str) -> float:
    """awk's string->number: the longest leading numeric prefix, else 0."""
    m = re.match(r"\s*[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?", field)
    return float(m.group(0)) if m else 0.0


def _awk_rows(path: Path):
    try:
        text = path.read_text(encoding="utf-8", errors="surrogateescape")
    except OSError:
        return []
    return [line.split("|") for line in text.split("\n")[:-1 if text.endswith("\n") else None]]


def _lines(text: str):
    """``while IFS= read -r line; do ...; done <<<"$text"``, skipping empty lines."""
    return [line for line in text.split("\n") if line]


def _pid_alive(pid: int) -> bool:
    """``kill -0``: fails for a dead pid *and* for another user's process."""
    try:
        os.kill(pid, 0)
    except (OSError, OverflowError):
        return False
    return True


def sidecar_path(target: str, suffix: str) -> str:
    """``.playing``/``.txt`` target -> ``<stem>.<suffix>`` (meta.json / viewer_memory.json)."""
    for ext in (".playing", ".txt"):
        if target.endswith(ext):
            return target[: -len(ext)] + "." + suffix
    return target + "." + suffix


def meta_sidecar_path(target: str) -> str:
    return sidecar_path(target, "meta.json")


def viewer_memory_sidecar_path(target: str) -> str:
    return sidecar_path(target, "viewer_memory.json")


def batch_metadata_path(batch_file: str) -> str:
    return f"{batch_file}.viewer_meta.jsonl"


_THUMBNAIL_PATTERNS = (
    r"画面|スクショ|スクリーン|映像|見え|見えて|表示|配信|サムネ|盤面",
    r"今の|いまの|現在|いまどう|今どう|どうなって|状況|状態",
    r"スコア|点数|記録|順位|rank|ランク|建国|ソ連|ロシア",
    r"type|ピース|next|ネクスト|hold|ホールド|デッドライン|ゲームオーバー",
)


def needs_thumbnail_context(comments: str) -> bool:
    return bool(comments) and any(re.search(p, comments, re.I) for p in _THUMBNAIL_PATTERNS)


def format_batch_context(text: str) -> str:
    """Per-comment neighbours block (the legacy stdout, blank line after each item)."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    items = []
    for ln in (raw.strip() for raw in text.splitlines()):
        if not ln:
            continue
        user, msg = ln.split(": ", 1) if ": " in ln else ("不明", ln)
        items.append((user.strip(), msg.strip(), ln))
    out = []
    for i, (user, msg, _raw) in enumerate(items, start=1):
        prev_raw = items[i - 2][2] if i > 1 else "（なし）"
        next_raw = items[i][2] if i < len(items) else "（なし）"
        same = "あり" if i > 1 and items[i - 2][0] == user else "なし"
        out += [f"[{i}] {user}: {msg}", f"  直前: {prev_raw}", f"  直後: {next_raw}",
                f"  直前が同一ユーザー: {same}", ""]
    return "".join(line + "\n" for line in out)


@dataclass
class CommentState:
    """The legacy comment state files under one Soren root (cwd in production)."""

    root: Path
    env: dict | None = None

    def __post_init__(self):
        self.root = Path(self.root)
        self.env = dict(os.environ if self.env is None else self.env)

    # -- paths -------------------------------------------------------------
    def _p(self, rel: str) -> Path:
        return self.root / rel

    @property
    def queue_dir(self) -> Path:
        return self._p("tmp/.comment_queue")

    @property
    def batch_history_file(self) -> Path:
        return self._p("tmp/.comment_queue/processed_batch_hashes.log")

    @property
    def inflight_file(self) -> Path:
        return self._p("tmp/.comment_queue/inflight_batch.log")

    @property
    def processed_lines_file(self) -> Path:
        return self._p("tmp/.comment_queue/processed_line_hashes.log")

    @property
    def spoken_history_dir(self) -> Path:
        return self._p("tmp/.comment_queue/spoken_history")

    @property
    def backoff_file(self) -> Path:
        explicit = self.env.get("COMMENT_FAILURE_BACKOFF_FILE")
        # The legacy expands ${TMP_STATE_DIR:-tmp/state}, but core/config.sh
        # always sets TMP_STATE_DIR=tmp/state.
        return self._p(explicit) if explicit else self._p("tmp/state/comment_generation_backoff_until")

    def _int_setting(self, *names, default: int) -> int:
        for name in names:
            value = self.env.get(name)
            if value:
                return int(value) if value.isdigit() else default
        return default

    # -- failure backoff -----------------------------------------------------
    def failure_backoff_remaining(self, now: int | None = None) -> int:
        now = int(time.time()) if now is None else now
        path = self.backoff_file
        if not path.is_file():
            return 0
        try:
            raw = path.read_text(encoding="utf-8").rstrip("\n")
        except OSError:
            raw = "0"
        until = int(raw) if raw.isdigit() and raw.isascii() else 0
        remaining = until - now
        if remaining <= 0:
            path.unlink(missing_ok=True)
            return 0
        return remaining

    def failure_backoff_set(self, seconds: int | str | None = None, now: int | None = None) -> None:
        now = int(time.time()) if now is None else now
        if seconds is None:
            seconds = self.env.get("COMMENT_FAILURE_BACKOFF_SEC") or self.env.get("AI_AGENT_BACKOFF_SEC") or "600"
        seconds = str(seconds)
        value = int(seconds) if seconds.isdigit() and seconds.isascii() else 600
        value = max(1, value)
        path = self.backoff_file
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(f"{path.name}.tmp.{os.getpid()}")
        tmp.write_text(f"{now + value}\n", encoding="utf-8")
        os.replace(tmp, path)

    def failure_backoff_clear(self) -> None:
        self.backoff_file.unlink(missing_ok=True)

    def handle_generation_failure(self, rate_limited: bool, now: int | None = None) -> None:
        """Only an explicit provider rate limit pauses comment generation."""
        if rate_limited:
            self.failure_backoff_set(None, now)
        else:
            self.failure_backoff_clear()

    # -- batch dedup ---------------------------------------------------------
    def is_recent_batch_processed(self, batch_hash: str, now: int | None = None) -> bool:
        now = int(time.time()) if now is None else now
        if not batch_hash or not self.batch_history_file.is_file():
            return False
        return any(len(f) >= 2 and f[1] == batch_hash and now - _awk_num(f[0]) <= COMMENT_BATCH_DEDUP_TTL
                   for f in _awk_rows(self.batch_history_file))

    def mark_batch_processed(self, batch_hash: str, now: int | None = None) -> None:
        now = int(time.time()) if now is None else now
        if not batch_hash:
            return
        kept = []
        for f in _awk_rows(self.batch_history_file):
            if (len(f) >= 2 and re.fullmatch(r"[0-9]+", f[0]) and now - int(f[0]) <= COMMENT_BATCH_DEDUP_TTL * 3
                    and f[1] != batch_hash):
                kept.append("|".join(f))
        kept.append(f"{now}|{batch_hash}")
        self.batch_history_file.parent.mkdir(parents=True, exist_ok=True)
        self.batch_history_file.write_text("".join(line + "\n" for line in kept), encoding="utf-8")

    # -- inflight --------------------------------------------------------------
    def _read_inflight(self):
        try:
            text = self.inflight_file.read_text(encoding="utf-8", errors="surrogateescape")
        except OSError:
            return None
        if "\n" not in text:
            return None  # `read` fails without a terminating newline
        ts, _, rest = text.split("\n", 1)[0].partition("|")
        batch_hash, _, pid = rest.partition("|")
        return ts, batch_hash, pid

    def is_batch_inflight(self, batch_hash: str, now: int | None = None) -> bool:
        now = int(time.time()) if now is None else now
        if not batch_hash or not self.inflight_file.is_file():
            return False
        record = self._read_inflight()
        if record is None:
            return False
        ts, recorded, pid = record
        if not re.fullmatch(r"[0-9]+", ts) or recorded != batch_hash:
            return False
        if now - int(ts) > COMMENT_BATCH_DEDUP_TTL:
            self.inflight_file.unlink(missing_ok=True)
            return False
        if not re.fullmatch(r"[0-9]+", pid):
            return True
        if _pid_alive(int(pid)):
            return True
        self.inflight_file.unlink(missing_ok=True)
        return False

    def mark_batch_inflight(self, batch_hash: str, pid: int | str = "", now: int | None = None) -> None:
        now = int(time.time()) if now is None else now
        if not batch_hash:
            return
        self.inflight_file.parent.mkdir(parents=True, exist_ok=True)
        self.inflight_file.write_text(f"{now}|{batch_hash}|{pid}\n", encoding="utf-8")

    def clear_batch_inflight(self, batch_hash: str = "") -> None:
        if not self.inflight_file.is_file():
            return
        if not batch_hash:
            self.inflight_file.unlink(missing_ok=True)
            return
        record = self._read_inflight()
        if record is None or record[1] == batch_hash:
            self.inflight_file.unlink(missing_ok=True)

    # -- per-line dedup ----------------------------------------------------------
    def _processed_hash_seen(self, line_hash: str, now: int) -> bool:
        return any(len(f) >= 2 and f[1] == line_hash and now - _awk_num(f[0]) <= COMMENT_PROCESSED_LINES_TTL
                   for f in _awk_rows(self.processed_lines_file))

    def filter_already_processed_lines(self, comments: str, now: int | None = None) -> str:
        now = int(time.time()) if now is None else now
        if not comments:
            return ""
        if not self.processed_lines_file.is_file():
            return comments
        kept = [line for line in _lines(comments) if not self._processed_hash_seen(hash_text(dedup_key(line)), now)]
        return "\n".join(kept)

    def has_processed_line(self, comments: str, now: int | None = None) -> bool:
        now = int(time.time()) if now is None else now
        if not comments or not self.processed_lines_file.is_file():
            return False
        return any(self._processed_hash_seen(hash_text(dedup_key(line)), now) for line in _lines(comments))

    def record_processed_lines(self, comments: str, now: int | None = None) -> None:
        now = int(time.time()) if now is None else now
        if not comments:
            return
        rows = [ "|".join(f) for f in _awk_rows(self.processed_lines_file)
                 if len(f) >= 2 and re.fullmatch(r"[0-9]+", f[0]) and now - int(f[0]) <= COMMENT_PROCESSED_LINES_TTL]
        rows += [f"{now}|{hash_text(dedup_key(line))}" for line in _lines(comments)]
        rows = rows[-COMMENT_PROCESSED_LINES_MAX:]
        self.processed_lines_file.parent.mkdir(parents=True, exist_ok=True)
        self.processed_lines_file.write_text("".join(row + "\n" for row in rows), encoding="utf-8")

    # -- backlog -------------------------------------------------------------------
    def backlog_counts(self) -> tuple[int, int]:
        """(queued ``comment_*.txt``, playing ``comment_*.playing``) in the queue dir."""
        try:
            names = [p.name for p in self.queue_dir.iterdir()]
        except OSError:
            return 0, 0
        queued = sum(1 for n in names if n.startswith("comment_") and n.endswith(".txt"))
        playing = sum(1 for n in names if n.startswith("comment_") and n.endswith(".playing"))
        return queued, playing

    def is_backlog_high(self, threshold: int = 4, basis: str = "total") -> bool:
        queued, playing = self.backlog_counts()
        return (queued if basis == "queued" else queued + playing) >= threshold

    # -- spoken history --------------------------------------------------------------
    def remember_reply_text(self, text: str, mode: str = "", *, now: float | None = None,
                            token: int | None = None) -> Path | None:
        """Keep the last N spoken replies (dedup by md5) for the recent-spoken context."""
        mode = "soren91" if mode == "soren91" else "main"
        if not text:
            return None
        directory = self.spoken_history_dir
        directory.mkdir(parents=True, exist_ok=True)
        keep = self._int_setting("COMMENT_SPOKEN_HISTORY_MAX_FILES", default=16)
        text_hash = hash_text(text)
        hash_file = directory / ".reply_hashes"
        try:
            if any(text_hash in line for line in hash_file.read_text(encoding="utf-8").split("\n")):
                return None
        except OSError:
            pass
        now = time.time() if now is None else now
        token = int.from_bytes(os.urandom(2), "big") & 0x7FFF if token is None else token
        stamp = datetime.fromtimestamp(now).strftime("%Y%m%d_%H%M%S")
        path = directory / f"{stamp}_{token}_{mode}.txt"
        path.write_text(text + "\n", encoding="utf-8")
        try:
            lines = hash_file.read_text(encoding="utf-8").split("\n")[:-1] if hash_file.exists() else []
        except OSError:
            lines = []
        lines = (lines + [text_hash])[-keep:]
        hash_file.write_text("".join(line + "\n" for line in lines), encoding="utf-8")
        # `ls -1t`: newest first, ties by name.
        files = sorted(directory.glob("*.txt"), key=lambda p: (-p.stat().st_mtime_ns, p.name))
        for old in files[keep:]:
            old.unlink(missing_ok=True)
        return path

    # -- generation meta ---------------------------------------------------------------
    @property
    def generation_history_file(self) -> Path:
        return self._p(f"{self.env.get('TMP_HISTORY_DIR') or 'tmp/history'}/comment_generation_history.jsonl")

    def store_generation_meta(self, target: str, *, mode: str, model: str, batch_hash: str, attempt,
                              chars, primary: str = "", secondary: str = "", tertiary: str = "",
                              speech_metadata_file: str = "", generated_at: str | None = None) -> dict:
        """Write the ``*.meta.json`` sidecar and append to the bounded generation history."""
        def to_int(raw) -> int:
            try:
                return int(raw)
            except Exception:
                return 0
        keep = max(1, to_int(self.env.get("COMMENT_GENERATION_HISTORY_KEEP") or "500") or 500)
        payload = {
            "generated_at": generated_at or datetime.now(timezone.utc).isoformat(),
            "target_file": target,
            "queue_file": os.path.basename(target),
            "mode": mode or "",
            "model": model or "unknown",
            "batch_hash": batch_hash or "",
            "attempt": to_int(attempt),
            "chars": to_int(chars),
            "chain": {"primary": primary or "", "secondary": secondary or "",
                      "tertiary": tertiary or "", "final": model or "unknown"},
        }
        if speech_metadata_file:
            with open(self._p(speech_metadata_file), encoding="utf-8") as stream:
                speech = json.load(stream)
            segments = speech.get("speech_segments")
            if not speech.get("bilingual") or not isinstance(segments, list) or not segments:
                raise ValueError("invalid bilingual speech metadata")
            payload["bilingual"] = True
            payload["speech_segments"] = segments
        sidecar = self._p(meta_sidecar_path(target))
        sidecar.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        history = self.generation_history_file
        history.parent.mkdir(parents=True, exist_ok=True)
        recent: deque[str] = deque(maxlen=max(0, keep - 1))
        if history.exists():
            try:
                with open(history, encoding="utf-8") as stream:
                    for line in stream:
                        line = line.rstrip("\n")
                        if line:
                            recent.append(line)
            except Exception:
                recent.clear()
        recent.append(json.dumps(payload, ensure_ascii=False))
        tmp = history.with_name(history.name + ".tmp")
        tmp.write_text("".join(line + "\n" for line in recent), encoding="utf-8")
        os.replace(tmp, history)
        return payload
