"""Performance evaluation for one declarative PAPER strategy experiment."""
from __future__ import annotations

from decimal import Decimal, InvalidOperation
from pathlib import Path
import sqlite3

from .models import as_decimal
from .strategy_lab import StrategyExperiment

D = Decimal


def _experiment_rows(db_path: Path, spec: StrategyExperiment):
    if not db_path.is_file():
        return []
    conn = None
    try:
        conn = sqlite3.connect(f"file:{db_path.resolve()}?mode=ro", uri=True)
        rows = conn.execute(
            """SELECT symbol, side, strategy_id, amount, price, filled_at
                 FROM paper_fills
                WHERE filled_at >= ?
                ORDER BY filled_at, rowid""",
            (float(spec.activated_at),),
        ).fetchall()
    except sqlite3.Error:
        return []
    finally:
        if conn is not None:
            conn.close()
    prefixes = (f"lab:{spec.experiment_id}:", f"lab-exit:{spec.experiment_id}:")
    result = []
    for symbol, side, strategy_id, amount, price, filled_at in rows:
        if not str(strategy_id).startswith(prefixes):
            continue
        try:
            result.append((
                str(symbol), str(side), str(strategy_id),
                D(str(amount)), D(str(price)), float(filled_at),
            ))
        except (InvalidOperation, ValueError, TypeError):
            continue
    return result


def evaluate_strategy_experiment(
    trading_dir,
    spec: StrategyExperiment,
    *,
    capital_jpy: object,
) -> dict[str, object]:
    """Evaluate only fills generated by ``spec``; unrelated PAPER trades are ignored."""
    rows = _experiment_rows(Path(trading_dir) / "paper.sqlite3", spec)
    lots: dict[str, list[Decimal]] = {}
    realized: list[Decimal] = []
    cumulative = D("0")
    peak = D("0")
    max_drawdown = D("0")
    ignored_unpaired_exits = 0

    for symbol, side, _strategy_id, amount, price, _filled_at in rows:
        held, cost = lots.setdefault(symbol, [D("0"), D("0")])
        if side == "buy":
            lots[symbol][0] = held + amount
            lots[symbol][1] = cost + amount * price
            continue
        if side != "sell" or held <= 0:
            if side == "sell":
                ignored_unpaired_exits += 1
            continue
        sold = min(amount, held)
        average = cost / held
        pnl = sold * (price - average)
        realized.append(pnl)
        cumulative += pnl
        peak = max(peak, cumulative)
        max_drawdown = max(max_drawdown, peak - cumulative)
        lots[symbol][0] = held - sold
        lots[symbol][1] = max(D("0"), cost - average * sold)

    gains = sum((value for value in realized if value > 0), D("0"))
    losses = -sum((value for value in realized if value < 0), D("0"))
    profit_factor = None if losses == 0 else gains / losses
    capital = as_decimal(capital_jpy, "capital_jpy")
    drawdown_pct = D("0") if capital <= 0 else max_drawdown / capital * D("100")
    wins = sum(1 for value in realized if value > 0)
    count = len(realized)

    return {
        "schema_version": 1,
        "experiment_id": spec.experiment_id,
        "activated_at": float(spec.activated_at),
        "closed_sells": count,
        "wins": wins,
        "win_rate": None if count == 0 else str(D(wins) / D(count)),
        "realized_pnl_jpy": str(cumulative),
        "profit_factor": None if profit_factor is None else str(profit_factor),
        "max_realized_drawdown_pct": str(drawdown_pct),
        "ignored_unpaired_exits": ignored_unpaired_exits,
        "promotion_ready": bool(
            count >= 20
            and cumulative > 0
            and profit_factor is not None
            and profit_factor >= D("1.20")
            and drawdown_pct <= D("10")
        ),
    }
